### ISSUE TITLE
Commentary

### ISSUE THREAD

**Issue by zackw** [martinthomson/postel-was-wrong#1]
I wrote a public commentary on this I-D at https://readings.owlfolio.org/2015/postel-was-wrong/ .

I would like to draw your attention particularly to the list of "real-world situations from the last couple decades of Internet protocol design that the author may or may not have considered."  These are all cases where (it seems to me) your proposed strictness principle may be incompatible with other desirable engineering goals, e.g. incremental deployment of extensions, author ergonomics, and security.  Explicit consideration of such cases would, IMHO, make your proposal stronger.  I'll summarize them here, but you may want to click through for the footnotes and so on:
- Reserved bits in TCP/IP packet headers, treated as must-be-zero by some routers, preventing incremental deployment of ECN
- TLS version intolerance (again, strictness versus incremental deployment)
- Padding oracles (in which fail-fast leads to a complete breach of confidentiality)
- The mandated error recovery behavior in both HTML5 and CSS

**Comment by martinthomson** [comment]
I think that the recent version takes a view that is more compatible with these cases, but I think you have a different problem here, at least for some of these example.  

Apparently ECN - as a mere 4 bit protocol - is remarkable in that it has been screwed up more than 16 different ways.  ECN failures and TLS version intolerance are prime examples of how lack of end-to-end protection of critical protocol signals can make what we now call "ossification" in the network possible.  The IAB has a [draft statement](https://datatracker.ietf.org/doc/html/draft-hardie-path-signals) on the principles that we believe apply in those cases.  Those same principles are driving the design of QUIC.

I spoke with Anne at some length about the error recovery part, and I think that the error in the previous versions of the draft was in being too binary about how errors are handled.  The error recovery in HTML5 and CSS is a core design feature.  The draft is now clearer about focusing on undefined behaviour - things that the specifications fails to address - more than it is about detecting errors.  The padding oracle thing is addressed as a consequence of that.
