### ISSUE TITLE
Spec lifecycle and specified permissiveness

### ISSUE THREAD

**Issue by mnot** [martinthomson/postel-was-wrong#2]
Two thoughts that might be worth considering integrating --

1) Many protocol development efforts, at their start, are under fairly extreme circumstances. There's a certain amount of hype about the "new thing", and yet reluctance to invest *too* much into it, in case it fails. At the same time, there's a rush to complete, so as to beat potential competitors to market, and to assure that sufficient resources (spec author, implementer, etc.) are available. 

All of this adds up to a tendency to write things down as quickly as possible; considering every corner case and design implication is seen as unnecessary, and putting the effort at additional risk.

HTTP/1.1 is an excellent example of this; RFC2616 was written down in a great rush, because the Web was "taking off." The httpbis effort took so long not because we were aligning the specs with the reality of implementation (as the current draft implies), but because we had to untangle a substantial mess (we also had to more precisely define for the corner cases, because HTTP was being used for more things -- which your draft does mention, at least generally).

httpbisbis might be the one where we tighten things up more substantially....

Conceptually, this is "protocol maintenance", if you expand the definition and give some background. I think of this in terms of precision of definition, which is apt to be loose at the beginning of a protocol's lifetime (but we can adopt some practices and tools to minimise this). 

2) There's a substantial body of experience that -- for some protocol artefacts -- permissive consumption is still necessary. In particular, formats that are produced by a large, non-technical or semi-technical set of authors need a fair amount of "slop." There are a lot of war stories in the XML community along these lines (happy to dig up some links).

I don't think this is that far from the current draft's content; it could be addressed by noting that these sorts of artefacts need permissiveness "built in"; i.e., they benefit from detailed, precise error handling defined up front. Waving your hands and saying "consume permissively" isn't good enough.

Happy to put some pull requests together, thought It'd be worth discussing first.

**Comment by britram** [comment]
A related observation occurs to me: some of the resistance to the notions in this draft are fundamentally tied to software development and deployment models that have changed dramatically, both within the Internet protocol design community (especially at the application layer and above), as well as in the wider industry. "Production" protocols today run with development cycles than would be considered faster than "experimental" in the waterfall-happy mid-1990s. It may be useful to note this explicitly.

**Comment by martinthomson** [comment]
This was good feedback.  I was unhappy with the fail noisily thesis and this helped crystalize a thought that I had in #3.  I've recast the problem in #5.

I see the "slop" thing as a necessary part of a specification of that nature - it is firmly in the design space.  The problem is not with tolerance in general, but with tolerance in reaction to shortcomings in the specification.  I think that I've made progress toward capturing that.

**Comment by martinthomson** [comment]
I've gotten good feedback about the current form of the draft thus far, thanks both for your input, it was a big help.
