### ISSUE TITLE
A New Design Principle

### ISSUE THREAD

**Issue by annevk** [martinthomson/postel-was-wrong#4]
I think https://www.w3.org/TR/html-design-principles/#interoperability is much preferable to this principle (though maybe not the exact words used).

1. "Undefined inputs" is a problem in the sense that the format/protocol should have an answer for all inputs. (That also gives you an extensibility story.)
2. "Fail noisily" is problematic as we don't necessarily want to expose end users to failures. And consider legacy clients encountering a new feature (undefined input?) should not necessarily fail or throw either.

To elaborate on 1, not dealing with erroneous/undefined inputs is common in IETF documents and causes all sorts of problems for:

* Text encodings (now largely solved by https://encoding.spec.whatwg.org/)
* URLs (see https://url.spec.whatwg.org/ for a solution)
* HTTP (see https://github.com/httpwg/http11bis/issues)
* MIME types (see https://github.com/whatwg/mimesniff/issues/30)

That has been far more harmful than "be liberal" has ever been. After all, you cannot even be liberal if all inputs have defined behavior.

**Comment by martinthomson** [comment]
The latest draft is a more fundamental statement about the robustness principle, that I think is now compatible with the HTML design principles.  One thing that I think is exemplified in the WHATWG specifications you cite here is that they are actively maintained.  A lot less is said about error reporting, though I still believe it to be critical in understanding where things went off the rails.
